theme: minima
title: Hannah's Learning How to Use GitHub!
author: hannah-sage
email: hannah@classiq.io
description: > # this means to ignore newlines until "baseurl:"
  I'm learning how to use GitHub! I work for an awesome company called Classiq Technologies,
  and I'm looking forward to using GitHub to communicate better with my incredible team!

# social links
linkedin_username: hannahsage # DO NOT include the @ character, or else the build will fail!
github_username:  hannah-sage # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
